function Strings(){}
Strings.AUTHENTICATION_NOT_CONFIGURED = 0;
Strings.AUTHORIZATION_NOT_CONFIGURED = 1;
Strings.UNAUTHORIZED = 2;
Strings.LOGIN_REQUIRED = 3;
Strings.INCORRECT_USER_NAME = 4;
Strings.INCORRECT_PASSWORD = 5;
Strings.LOGIN_SUCCESSFUL = 6;
Strings.LISTENING_ON_PORT = 7;

module.exports = Strings;

