const strings = [
    'Login successful.',
    'Listening on port {1}.',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'Authentication not configured.',
    'Authorization not configured.',
    'Unauthorized.',
    'Login required.',
    'Incorrect username: {1}.',
    'Incorrect password.',
    'Login Expired.',
    '{1}',
    'Conflict: File {1} Already Exists.'
];

module.exports = strings;
