const strings = [
    'Login successful.',
    'Listening on port {1}.',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'Authentication not configured.',
    'Authorization not configured.',
    'Unauthorized.',
    'Login required.',
    'Incorrect username: {0}.',
    'Incorrect password.',
    'At least one group is required.',
    'Login Expired.',
    '{1}',
    'Conflict: File {1} Already Exists.',
    'Account added successfully.',
    'Add account failed. Error: {0}',
    'Add account is not properly configured. A destination is required.'
];

module.exports = strings;
