const strings = [
    'Login successful.',
    'Listening on port {1}.',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'RESERVED',
    'Authentication not configured.',
    'Authorization not configured.',
    'Unauthorized.',
    'Login required.',
    'Incorrect username: {0}.',
    'Incorrect password.',
    'At least one group is required.',
    'Login Expired.',
    '{1}',
    'Conflict: File {1} Already Exists.',
    'Account added successfully.',
    'Add account failed. Error: {0}',
    'Add account is not properly configured. A destination is required.',
    'Favorite added.',
    'Add favorite failed. Error: {0}',
    'Favorite deleted.',
    'Delete favorite failed. Error: {0}',
    'Cart item added.',
    'Add to cart failed. Error: {0}',
    'Cart item deleted.',
    'Delete from cart failed. Error: {0}',
];

module.exports = strings;
